# Generated by Django 4.0.4 on 2022-06-05 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0004_alter_usuarios_id_grupo_alter_usuarios_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rfc', models.CharField(max_length=50, verbose_name='RFC')),
            ],
            options={
                'permissions': [('crea_grupo', 'Crea grupo')],
                'proxy': False,
            },
            bases=('plannet.usuarios',),
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('ingresa_grupo', 'Ingresa a grupo')],
                'proxy': False,
            },
            bases=('plannet.usuarios',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('boleta', models.CharField(max_length=50, verbose_name='Boleta')),
            ],
            options={
                'permissions': [('ingresa_grupo', 'Ingresa a grupo')],
                'proxy': False,
            },
            bases=('plannet.usuarios',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rfc', models.CharField(max_length=50, verbose_name='RFC')),
                ('clave_institucion', models.CharField(max_length=50, verbose_name='Clavedeinstitucion')),
            ],
            options={
                'permissions': [('crea_grupo', 'Crea grupo')],
                'proxy': False,
            },
            bases=('plannet.usuarios',),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='nombre_grupo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre_grupo'),
        ),
    ]
