# Generated by Django 4.0.4 on 2022-06-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0005_coach_emprendedor_estudiante_profesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='rfc',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='boleta',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Boleta'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='clave_institucion',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Clavedeinstitucion'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='rfc',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='RFC'),
        ),
    ]
