# Generated by Django 4.0.4 on 2022-06-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0009_remove_grupos_id_integrante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Campo')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
            ],
        ),
        migrations.AlterModelOptions(
            name='grupos',
            options={'ordering': ['id', 'nombre_grupo'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.CreateModel(
            name='EstadosFinancieros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del estado')),
                ('id_contenido_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plannet.contenidoestados')),
            ],
        ),
    ]
