# Generated by Django 4.0.4 on 2022-06-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0010_contenidoestados_alter_grupos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosfinancieros',
            options={'ordering': ['id', 'nombre_estado'], 'verbose_name': 'Estado Financiero', 'verbose_name_plural': 'Estados Financieros'},
        ),
    ]
