# Generated by Django 4.0.4 on 2022-06-07 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0014_contenidoestados_agrupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Materia prima o materiales')),
                ('unidad_medida', models.CharField(blank=True, choices=[('1', 'Pieza'), ('2', 'Caja'), ('3', 'Barril'), ('4', 'Litro'), ('5', 'Kilogramo')], default=1, max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contenidoestados',
            name='id_estado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Contenido', to='plannet.estadosfinancieros'),
        ),
        migrations.AlterField(
            model_name='estadousuario',
            name='id_usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Estado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlandeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tema')),
                ('subtema', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtema')),
                ('actividad', models.FileField(default='', null=True, upload_to='images/', verbose_name='Actividad')),
                ('puntuacion', models.IntegerField(blank=True, null=True, verbose_name='Puntuación')),
                ('comentario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Comentario')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Producto')),
                ('unidades', models.IntegerField(blank=True, null=True, verbose_name='Unidades al año')),
                ('precio_unitario', models.IntegerField(blank=True, null=True, verbose_name='Precio unitario')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Ingresos', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Ingresos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
