# Generated by Django 4.0.4 on 2023-01-12 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=50, unique=True, verbose_name='Correo')),
                ('foto', models.ImageField(default='', null=True, upload_to='images/', verbose_name='Foto')),
                ('num', models.CharField(max_length=50, verbose_name='Núm. de boleta o empleado')),
                ('tipo', models.CharField(blank=True, choices=[('1', 'Estudiante'), ('2', 'Profesor')], default=1, max_length=1, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id', 'nombre'],
                'permissions': [('ingresa_grupo', 'Ingresa a grupo'), ('crea_grupo', 'Crea grupo')],
            },
        ),
        migrations.CreateModel(
            name='ContenidoEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fila')),
                ('columna', models.CharField(blank=True, max_length=50, null=True, verbose_name='Columna')),
                ('agrupacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Agrupación')),
                ('numero_campo', models.IntegerField(blank=True, null=True, verbose_name='Numero de campo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadosFinancieros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del estado')),
            ],
            options={
                'verbose_name': 'Estado Financiero',
                'verbose_name_plural': 'Estados Financieros',
                'ordering': ['id', 'nombre_estado'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'proxy': False,
            },
            bases=('plannet.usuarios',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'proxy': False,
            },
            bases=('plannet.usuarios',),
        ),
        migrations.CreateModel(
            name='PlandeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tema')),
                ('subtema', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtema')),
                ('actividad', models.FileField(default='', null=True, upload_to='images/', verbose_name='Actividad')),
                ('puntuacion', models.IntegerField(blank=True, null=True, verbose_name='Puntuación')),
                ('comentario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Comentario')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Materia prima o materiales')),
                ('unidad_medida', models.CharField(blank=True, choices=[('1', 'Pieza'), ('2', 'Caja'), ('3', 'Barril'), ('4', 'Litro'), ('5', 'Kilogramo'), ('6', 'Paquete')], default=1, max_length=1, null=True)),
                ('costo', models.IntegerField(blank=True, null=True, verbose_name='Costo por unidad')),
                ('volumen', models.IntegerField(blank=True, null=True, verbose_name='Volumen requerido')),
                ('costo_anual', models.IntegerField(blank=True, null=True, verbose_name='Costo por año')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Materiales', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Materiales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del puesto')),
                ('numero_trabajadores', models.IntegerField(blank=True, null=True, verbose_name='Número de trabajadores')),
                ('pago_mensual', models.IntegerField(blank=True, null=True, verbose_name='Pago mensual')),
                ('pago_anual', models.IntegerField(blank=True, null=True, verbose_name='Pago anual')),
                ('prestaciones', models.IntegerField(blank=True, null=True, verbose_name='Prestaciones 30%')),
                ('total_anual', models.IntegerField(blank=True, null=True, verbose_name='Total anual')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_ManoObra', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_ManoObra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inversion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de inversión')),
                ('socios', models.IntegerField(blank=True, null=True, verbose_name='Inversión de socios')),
                ('bancos', models.IntegerField(blank=True, null=True, verbose_name='Inversión de bancos')),
                ('gobiernof', models.IntegerField(blank=True, null=True, verbose_name='Inversión de gobierno federal')),
                ('gobiernoe', models.IntegerField(blank=True, null=True, verbose_name='Inversión de gobierno estatal')),
                ('otras', models.IntegerField(blank=True, null=True, verbose_name='Otras inversiones')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Inversion', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Inversion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Producto')),
                ('unidades', models.IntegerField(blank=True, null=True, verbose_name='Unidades al año')),
                ('precio_unitario', models.IntegerField(blank=True, null=True, verbose_name='Precio unitario')),
                ('ingresos', models.IntegerField(blank=True, null=True, verbose_name='Ingresos por año')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Ingresos', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Ingresos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=50, verbose_name='Nombre del grupo')),
                ('clave', models.CharField(default=1, max_length=50, unique=True, verbose_name='Clave')),
                ('periodo', models.CharField(blank=True, choices=[('1', 'enero-junio'), ('2', 'agosto-diciembre')], default=1, max_length=1, null=True)),
                ('ciclo', models.CharField(max_length=50, null=True, verbose_name='Año')),
                ('id_responsable', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['id', 'nombre_grupo'],
            },
        ),
        migrations.CreateModel(
            name='GastoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_venta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción del gastode venta')),
                ('unidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de medida')),
                ('gasto_unidad', models.IntegerField(blank=True, null=True, verbose_name='Gasto por unidad')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad requerida')),
                ('gasto_anual', models.IntegerField(blank=True, null=True, verbose_name='Gasto por año')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_GastoVenta', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_GastoVenta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastoAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del puesto')),
                ('numero_personas', models.IntegerField(blank=True, null=True, verbose_name='Número de personas')),
                ('pago_mensual', models.IntegerField(blank=True, null=True, verbose_name='Pago mensual')),
                ('pago_anual', models.IntegerField(blank=True, null=True, verbose_name='Pago anual')),
                ('prestaciones', models.IntegerField(blank=True, null=True, verbose_name='Prestaciones 30%')),
                ('total_anual', models.IntegerField(blank=True, null=True, verbose_name='Total anual')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_GastoAdministracion', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_GastoAdministracion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('id_campo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Campo', to='plannet.contenidoestados')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Estado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_ventas', models.IntegerField(blank=True, null=True, verbose_name='Costo de ventas')),
                ('materias_primas', models.IntegerField(blank=True, null=True, verbose_name='Materias Primas')),
                ('mano_obra', models.IntegerField(blank=True, null=True, verbose_name='Mano de obra')),
                ('utilidad_bruta', models.IntegerField(blank=True, null=True, verbose_name='Utilidad bruta')),
                ('gastos_generales', models.IntegerField(blank=True, null=True, verbose_name='Gastos generales')),
                ('gastos_administracion', models.IntegerField(blank=True, null=True, verbose_name='Gastos de administración')),
                ('gastos_venta', models.IntegerField(blank=True, null=True, verbose_name='Gastos de venta')),
                ('utilidad_antes_impuestos', models.IntegerField(blank=True, null=True, verbose_name='Utiidad antes de impuestos')),
                ('impuesto', models.IntegerField(blank=True, null=True, verbose_name='Impuesto a la utilidad')),
                ('utilidad_neta', models.IntegerField(blank=True, null=True, verbose_name='Utilidad neta')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_EstadoResultados', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_EstadoResultados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envase', models.CharField(blank=True, choices=[('1', 'Envase'), ('2', 'Empaque'), ('3', 'Embalaje')], default=1, max_length=1, null=True)),
                ('volumen', models.IntegerField(blank=True, null=True, verbose_name='Volumen de productos')),
                ('necesidad', models.IntegerField(blank=True, null=True, verbose_name='Necesidad de envase')),
                ('costo', models.IntegerField(blank=True, null=True, verbose_name='Costo unitario')),
                ('costo_anual', models.IntegerField(blank=True, null=True, verbose_name='Costo anual')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Envase', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Envase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contenidoestados',
            name='id_estado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Contenido', to='plannet.estadosfinancieros'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plannet.grupos'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
