# Generated by Django 4.0.4 on 2023-01-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosfinancieros',
            name='fase',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='nombre_estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la actividad'),
        ),
    ]
