# Generated by Django 4.0.4 on 2023-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0002_contenidoestados_estadosfinancieros_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nombreusuario',
            field=models.CharField(max_length=50, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='num',
            field=models.CharField(max_length=50, verbose_name='Número de empleado o boleta'),
        ),
    ]
