# Generated by Django 4.0.4 on 2022-05-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0002_alter_usuarios_options_usuarios_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
