# Generated by Django 4.0.4 on 2023-01-13 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0002_estadosfinancieros_fase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Producto')),
                ('tipo', models.CharField(blank=True, choices=[('1', 'Software'), ('2', 'Hardware'), ('3', 'Sistema embebido')], default=1, max_length=1, null=True)),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Definicion', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Definicion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
