# Generated by Django 4.0.4 on 2022-05-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0003_usuarios_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plannet.grupos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1', 'Estudiante'), ('2', 'Emprendedor'), ('3', 'Profesor'), ('4', 'Coach')], default=1, max_length=1, null=True),
        ),
    ]
