# Generated by Django 4.0.4 on 2023-01-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0003_definicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='definicion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion'),
        ),
    ]
