# Generated by Django 4.0.4 on 2023-01-13 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0004_definicion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definicion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Definición'),
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(blank=True, max_length=50, null=True, verbose_name='Misión')),
                ('vision', models.CharField(blank=True, max_length=50, null=True, verbose_name='Visión')),
                ('objgeneral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objetivo general')),
                ('objespecificos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Objetivos específicos')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Objetivos', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Ojetivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
