# Generated by Django 4.0.4 on 2023-01-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0005_alter_definicion_descripcion_objetivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivos',
            name='mision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='objgeneral',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Objetivo general'),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='vision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visión'),
        ),
    ]
