# Generated by Django 4.0.4 on 2022-06-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0006_alter_coach_rfc_alter_estudiante_boleta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emprendedor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['id', 'nombre'], 'permissions': [('ingresa_grupo', 'Ingresa a grupo'), ('crea_grupo', 'Crea grupo')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
