# Generated by Django 4.0.4 on 2023-01-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0006_alter_objetivos_mision_alter_objetivos_objgeneral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('1', 'Unidad'), ('2', 'Mes de servicio'), ('3', 'Año de servicio')], default=1, max_length=1, null=True),
        ),
    ]
