# Generated by Django 4.0.4 on 2023-01-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0007_alter_materiales_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='bancos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inversión de bancos'),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='gobiernoe',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inversión de gobierno estatal'),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='gobiernof',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inversión de gobierno federal'),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='otras',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Otras inversiones'),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='socios',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inversión de socios'),
        ),
    ]
