# Generated by Django 4.0.4 on 2023-01-13 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0008_alter_inversion_bancos_alter_inversion_gobiernoe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Volumen de productos')),
                ('tipo_requerimiento', models.CharField(blank=True, choices=[('1', 'Funcional'), ('2', 'No funcional')], default=1, max_length=1, null=True)),
                ('Requerimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción del requerimiento')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Requerimientos', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Requerimientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
