# Generated by Django 4.0.4 on 2023-01-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0010_retroalimentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='definicion',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('1', 'Producto'), ('2', 'Servicio')], default=1, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='definicion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='definicion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='retroalimentacion',
            name='calificacion',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=1, max_length=2, null=True),
        ),
    ]
