# Generated by Django 4.0.4 on 2022-06-07 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0011_alter_estadosfinancieros_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidoestados',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='estadosfinancieros',
            name='id_contenido_estado',
        ),
        migrations.AddField(
            model_name='contenidoestados',
            name='id_estado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='plannet.estadosfinancieros'),
        ),
        migrations.AddField(
            model_name='contenidoestados',
            name='numero_campo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de campo'),
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('id_campo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Campo', to='plannet.contenidoestados')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
