# Generated by Django 4.0.4 on 2023-01-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0011_definicion_clasificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivos',
            name='mision',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='objespecificos',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Objetivos específicos'),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='objgeneral',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Objetivo general'),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='vision',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Visión'),
        ),
    ]
