# Generated by Django 4.0.4 on 2022-06-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0012_remove_contenidoestados_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidoestados',
            name='campo',
        ),
        migrations.AddField(
            model_name='contenidoestados',
            name='columna',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Columna'),
        ),
        migrations.AddField(
            model_name='contenidoestados',
            name='fila',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fila'),
        ),
    ]
