# Generated by Django 4.0.4 on 2023-01-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0013_disarquitectura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gantt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(blank=True, choices=[('1', 'Planeación'), ('2', 'Análisis'), ('3', 'Diseño'), ('4', 'Desarrollo'), ('5', 'Pruebas'), ('6', 'Implementación'), ('7', 'Cierre del proyecto')], default=1, max_length=1, null=True)),
                ('numtarea', models.IntegerField(blank=True, null=True, verbose_name='Número de tarea')),
                ('asignado', models.CharField(blank=True, max_length=80, null=True, verbose_name='Asignado a')),
                ('estado', models.CharField(blank=True, choices=[('1', 'No iniciada'), ('2', 'En progreso'), ('3', 'Finalizada')], default=1, max_length=1, null=True)),
                ('fechaini', models.DateField()),
                ('fechafin', models.DateField()),
                ('notas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notas y comentarios')),
                ('predecesora', models.IntegerField(blank=True, null=True, verbose_name='Tarea predecesora')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Gantt', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Gantt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Documentacion', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Documentacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActPruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_ActPruebas', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_ActPruebas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActDespliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_ActDespliegue', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_ActDespliegue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
