# Generated by Django 4.0.4 on 2023-01-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0014_gantt_documentacion_actpruebas_actdespliegue'),
    ]

    operations = [
        migrations.AddField(
            model_name='definicion',
            name='id_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plannet.grupos'),
        ),
    ]
