# Generated by Django 4.0.4 on 2023-01-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0015_definicion_id_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt',
            name='fechafin',
            field=models.DateField(verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fechaini',
            field=models.DateField(verbose_name='Fecha inicial'),
        ),
        migrations.AlterField(
            model_name='retroalimentacion',
            name='calificacion',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=1, null=True),
        ),
    ]
