# Generated by Django 4.0.4 on 2023-01-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0016_alter_gantt_fechafin_alter_gantt_fechaini_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroalimentacion',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='num',
            field=models.CharField(max_length=50, verbose_name='Núm. de boleta'),
        ),
    ]
