# Generated by Django 4.0.4 on 2022-06-08 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0016_ingresos_ingresos_materiales_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inversion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de inversión')),
                ('socios', models.IntegerField(blank=True, null=True, verbose_name='Inversión de socios')),
                ('bancos', models.IntegerField(blank=True, null=True, verbose_name='Inversión de bancos')),
                ('gobiernof', models.IntegerField(blank=True, null=True, verbose_name='Inversión de gobierno federal')),
                ('gobiernoe', models.IntegerField(blank=True, null=True, verbose_name='Inversión de gobierno estatal')),
                ('otras', models.IntegerField(blank=True, null=True, verbose_name='Otras inversiones')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado_Inversion', to='plannet.estadosfinancieros')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Inversion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
