# Generated by Django 4.0.4 on 2023-01-20 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannet', '0019_alter_inversion_tipo_inversion_alter_manoobra_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
                ('id_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Reportar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
